* sms-box (WIP)
** Introduction
This repo contains a set of tools intended for Sega Master System
homebrew development. The following tools are included:

 - ~wla-dx~, a multi-platform assembler with its own linker and z80
   support.
 - ~meka~, a Sega Master System emulator.
 - ~z80-mode~, a z80 assembly Emacs syntax highlighting mode.
 - A hello world example with a simple Makefile.
 - A handful of documentation regarding SMS and z80.

** Prerequisites
*** meka
 - Allegro5
 - g++
*** wla-dx
 - cmake


** Installation
First, clone the whole repo with its submodules using ~git clone
--recurse-submodules -j8 https://github.com/samgh96/sms-box~.

Then, install all prerequisites. After that, just run ~install.sh~.

After the installation your Sega Master System environment will be
located in ~/opt/sms-box~. Add the following lines to your ~.rc~ file
in order to make ~sms-box~ easy to use:
#+BEGIN_SRC bash
export PATH=/opt/sms-box/wla-dx/build/binaries:/opt/sms-box/meka/meka:$PATH
alias mekarun=/opt/sms-box/meka/meka/meka
#+END_SRC

** TODO Things to be done
 - Put everything in a container (if possible).
 - Make a z80 init file for SMS.
 - Read all .txt files in docs and convert them to markdown or org-mode.
 - Use only z80 + linker in ~wla-dx~ installation.
** Useful links
Currently almost everything in this repository is extracted or slightly
modified from https://www.smspower.org/Development/
