* sms-box (WIP)
** Introduction
This repo contains a set of tools intended for Sega Master System
homebrew development. The following tools are included:

 - ~wla-dx~, a multi-platform assembler with its own linker and z80
   support.
 - ~meka~, a Sega Master System emulator.
 - ~z80-mode~, a z80 assembly Emacs syntax highlighting mode.
 - A hello world example with a simple Makefile.
 - A handful of documentation regarding SMS and z80.

** Installation
First, clone the whole repo with its submodules using ~git clone
--recurse-submodules -j8 https://github.com/samgh96/sms-box~.

Then, execute the commands written in the "Install commands" section
(this will be a custom script).

** TODO Things to be done
 - Put everything in a container (if possible).
 - Make a z80 init file for SMS.
 - Read all .txt files in docs and convert them to markdown or org-mode.
** Prerequisites
*** meka
 - Allegro5
 - g++
*** wla-dx
 - cmake
** Install commands
#+BEGIN_SRC bash
# ---- build wla-dx ----
cd wla-dx
mkdir build && cd build
cmake ..
cmake --build . --config Release
# optional: install wla-dx in /usr/bin
# sudo cmake -P cmake_install.cmake
# ---- build blastem ----
# cd ../../blastem
# make
# ---- build meka ----
cd meka/meka/srcs
make
# ---- optional: add z80-mode to your emacs config (if you use emacs) ----
if [[ ! -f $HOME/.emacs.d/z80-mode.el ]]; then

  curl -o $HOME/.emacs.d/z80-mode.el https://raw.githubusercontent.com/SuperDisk/z80-mode/master/z80-mode.el

  if [[ -f $HOME/.emacs.d/init.el ]]; then
    echo "(if (file-exists-p \"${HOME}/.emacs.d/z80-mode.el\") (load-file \"${HOME}/.emacs.d/z80-mode.el\"))" >> $HOME/.emacs.d/init.el
  fi

fi
#+END_SRC
